package xiroc.deltahard;

import java.io.File;
import java.util.ArrayList;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import net.minecraft.init.Blocks;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.relauncher.Side;
import xiroc.deltahard.common.network.PacketClientExplosion;
import xiroc.deltahard.common.util.ConfigCache;
import xiroc.deltahard.common.util.Config;
import xiroc.deltahard.common.util.EventManager;
import xiroc.deltahard.common.util.Reference;
import xiroc.deltahard.common.world.WorldGenMonsterEgg;

@Mod(modid = Reference.MODID, name = Reference.NAME, version = Reference.VERSION, acceptedMinecraftVersions = Reference.MINECRAFTVERSIONS)
public class DeltaHard {

	public static final Logger logger = LogManager.getLogger("DeltaHard");
	
	private static int PACKETS = 0;
	public static final SimpleNetworkWrapper NET = NetworkRegistry.INSTANCE.newSimpleChannel("deltahardmode");

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		
		logger.info("HELLO WORLD");
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.name = TextFormatting.RED + "" + TextFormatting.BOLD + "Delta Hard Mode";
		data.version = Reference.VERSION_STRING;
		data.authorList.add(Reference.AUTHOR);
		data.credits = Reference.CREDITS;
		data.url = "http://xiroc.ovh/deltahardmode/deltahardmode";
		data.description = TextFormatting.RED + "There will be some json syntax exceptions when loading a world due to removed recipes. This is not a problem and there is currently no way to avoid that.";
		MinecraftForge.EVENT_BUS.register(new EventManager());
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		Config.loadConfig();
		ConfigCache.load();
		GameRegistry.registerWorldGenerator(new WorldGenMonsterEgg(), 1);
		NET.registerMessage(PacketClientExplosion.MessageHandlerClientExplosion.class, PacketClientExplosion.class, PACKETS++, Side.CLIENT);
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		Reference.checkForNewVersion();
	}

}
